export const storeItems = [
  { id: 1, name: "Acessório para fixação vertical", category: "loja", image: "fixacao.png", preco: 25.0 },
  { id: 2, name: "Barra de estrutura", category: "loja", image: "barra.png", preco: 30.0 },
  { id: 3, name: "Estrutura para solo", category: "loja", image: "solo.png", preco: 45.0 },
  { id: 4, name: "Fixador de grampo", category: "loja", image: "grampo.png", preco: 10.0 },
  { id: 5, name: "Conector em grampo", category: "loja", image: "conector.png", preco: 12.5 },
  { id: 6, name: "Junção", category: "loja", image: "juncao.png", preco: 15.0 },
  { id: 7, name: "Junção em U", category: "loja", image: "juncaoU.png", preco: 18.0 },
  { id: 8, name: "Placas para piscina", category: "loja", image: "piscina.png", preco: 80.0 },
  { id: 9, name: "Suporte central", category: "loja", image: "suporte.png", preco: 22.0 },
  { id: 10, name: "Braçadeira", category: "loja", image: "bracadeira.png", preco: 8.0 },
  { id: 11, name: "Orgânicos", category: "placas", image: "organicos.png", preco: 120.0 },
  { id: 12, name: "Perovskita", category: "placas", image: "perovskita.png", preco: 150.0 },
  { id: 13, name: "DSSC", category: "placas", image: "dssc.png", preco: 130.0 },
];
